### ISSUE TITLE
Dosent work

### ISSUE THREAD

**Issue by Frzifus** [KnutZuidema/ADS#1] opened 2018-04-12 20:35 UTC
`-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:16 (add_executable):
  add_executable called with incorrect number of arguments

-- Configuring incomplete, errors occurred!
See also "/home/frzifus/git/ADS/CMakeFiles/CMakeOutput.log".`

**Comment by KnutZuidema** [comment] 2018-04-12 20:54
Can't reproduce, please provide more information

**Comment by KnutZuidema** [comment] 2018-04-12 21:10
Please use the new [issue template](https://github.com/KnutZuidema/ADS/blob/master/ISSUE_TEMPLATE.md) and edit your issue or open a new one.

**Comment by KnutZuidema** [comment] 2018-04-13 10:00
Found the problem. There was an add_executable() command in the CMake project for a test executable I used earlier. Update via git and the problem should be fixed.

**Closed** 2018-04-13 10:00 UTC
Labels: invalid
